spring:
  mail:
    host: smtp.163.com
    port: 25
    username: 18264180308@163.com
    password: lin199411083952
    protocol: smtp
    default-encoding: utf-8
mail:
  send-from: 18264180308@163.com
  send-by: Cohen
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring-profiles-active: dev